### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by givememulch** [vendz/fmovies-api#4]
hey there, I'm wanting to use this api but im wondering if I need to build this project for it to work or something. 

I would like to use it like this: https://fmovies-api.vercel.app/search?query=Stranger+Things
but it doesn't give any information whenever I use the api. I think im doing something wrong but im just wondering how exactly does this work. Do i need to register for something?

Thanks.

**Comment by vendz** [comment]
firstly, you need to use `keyword` instead of `query` and for usage info please go through the readme file.

regarding the response issue:-
 - there is some scraping issue that needs to fixed due to changes in the domain but this is project is no longer being maintained so if you figure out the issue and want to collaborate just create a pull request and I'll merge it

**Comment by givememulch** [comment]
Is there any place i can message you privately?
